version: '3'

services:
  bot:
    container_name: bot
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_NAME=bot.db
    restart: always