"""upgrade user table

Revision ID: 083d5cc61a04
Revises: 26b316bb0c6d
Create Date: 2025-03-30 21:05:51.501721

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "083d5cc61a04"
down_revision: Union[str, None] = "26b316bb0c6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usermodel",
        sa.Column("user_phone", sa.String(length=25), nullable=True),
    )
    op.create_index(
        op.f("ix_usermodel_user_phone"),
        "usermodel",
        ["user_phone"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usermodel_user_phone"), table_name="usermodel")
    op.drop_column("usermodel", "user_phone")
    # ### end Alembic commands ###
