"""init project

Revision ID: 2b6c40afc75e
Revises: 
Create Date: 2025-04-07 22:17:16.035761

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b6c40afc75e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usertypemodel",
        sa.Column("name_type", sa.String(length=60), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "usermodel",
        sa.Column("id_user_type", sa.Integer(), nullable=False),
        sa.Column("user_name", sa.String(length=255), nullable=False),
        sa.Column("user_phone", sa.String(length=25), nullable=True),
        sa.Column("post", sa.String(length=200), nullable=True),
        sa.Column("tg_id", sa.BigInteger(), nullable=True),
        sa.Column("date_start", sa.Date(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["id_user_type"],
            ["usertypemodel.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usermodel_post"), "usermodel", ["post"], unique=False)
    op.create_index(op.f("ix_usermodel_tg_id"), "usermodel", ["tg_id"], unique=False)
    op.create_index(
        op.f("ix_usermodel_user_phone"),
        "usermodel",
        ["user_phone"],
        unique=False,
    )
    op.create_table(
        "meetmodel",
        sa.Column("id_who", sa.Integer(), nullable=False),
        sa.Column("id_with", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("date_meeting", sa.DateTime(), nullable=True),
        sa.Column("time_format", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["id_who"],
            ["usermodel.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_with"],
            ["usermodel.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meetmodel")
    op.drop_index(op.f("ix_usermodel_user_phone"), table_name="usermodel")
    op.drop_index(op.f("ix_usermodel_tg_id"), table_name="usermodel")
    op.drop_index(op.f("ix_usermodel_post"), table_name="usermodel")
    op.drop_table("usermodel")
    op.drop_table("usertypemodel")
    # ### end Alembic commands ###
