"""upd: user model

Revision ID: 3a5ccfb479e1
Revises: 4829696e7ecc
Create Date: 2025-03-31 23:20:09.538696

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3a5ccfb479e1"
down_revision: Union[str, None] = "4829696e7ecc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usermodel", "user_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usermodel",
        sa.Column("user_name", sa.VARCHAR(length=255), nullable=False),
    )
    # ### end Alembic commands ###
