"""initial migrate

Revision ID: d59324b62748
Revises: 9a3986c5e60e
Create Date: 2025-03-30 18:06:47.729218

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d59324b62748"
down_revision: Union[str, None] = "9a3986c5e60e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usertypemodel",
        sa.Column("name_type", sa.String(length=60), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "usermodel",
        sa.Column("id_user_type", sa.Integer(), nullable=False),
        sa.Column("user_name", sa.String(length=255), nullable=False),
        sa.Column("tg_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_user_type"],
            ["usertypemodel.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_usermodel_tg_id"), "usermodel", ["tg_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usermodel_tg_id"), table_name="usermodel")
    op.drop_table("usermodel")
    op.drop_table("usertypemodel")
    # ### end Alembic commands ###
